name: munadi
adopt-info: munadi
base: core18
confinement: strict
grade: stable
apps:
  munadi:
    command: desktop-launch munadi
    common-id: org.munadi.Munadi
    autostart: org.munadi.Munadi.desktop
    plugs: [home, network, unity7, opengl, mir, audio-playback, desktop, desktop-legacy]
    environment: 
      DISABLE_WAYLAND: 1
parts:
  munadi:
    after: [desktop-qt5]
    plugin: qmake
    source-type: git
    source-tag: '20.09.1'
    source-subdir: src
    source: https://gitlab.com/munadi/munadi.git
    parse-info: [usr/share/metainfo/org.munadi.Munadi.metainfo.xml]
    build-packages:
      - g++
      - make
      - ccache
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtlocation5-dev
      - qtmultimedia5-dev
      - qtpositioning5-dev
      - qtquickcontrols2-5-dev
      - qttools5-dev-tools
    stage-packages:
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls
      - qml-module-qt-labs-platform
      - qml-module-qtquick-controls2
      - qml-module-qtmultimedia
      - qml-module-qt-labs-settings
      - qml-module-qtlocation
      - qml-module-qtpositioning
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - qml-module-qtgstreamer
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - qtwayland5
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
